

/* Generalized Estimating Equation GEE */
PROC GENMOD DATA=X DESCENDING;
 CLASS patient_ID variable TIME;
 MODEL RESP= variable TIME variable*TIME /
 LINK= LOGIT DIST=Binomial;
 REPEATED SUBJECT= patient_ID / TYPE=UN:
 LSMEANS variable*TIME / DIFFS ILINK;
 ODS OUTPUT LSMEANS=_LSMEANSG;
 ODS OUTPUT DIFFS=_DIFFSG;
RUN;

 
/* Pseudo-likelihood */
PROC GLIMMIX DATA=X METHOD=RPML;
 NLOPTIONS MAXITER=100 TECHNIQUE=NEWRAP;
 CLASS patient_ID variable TIME;
 MODEL RESP= variable TIME variable*TIME /
 LINK= LOGIT DIST=Binomial;
 Random TIME / SUBJECT=patient_ID RESIDUAL TYPE=UN V VCORR;
 LSMEANS variable*TIME / DIFFS ILINK;
 ODS OUTPUT LSMEANS=_LSMEANS DIFFS=_DIFFS V=_V VCORR=_VCORR;
RUN;

  
 